In [8]:
import numpy as np
x =  np.arange(11, 20).reshape(3,3)
y =  np.arange(15,24).reshape(3,3)


print("First Matrix:")
print(x)


print("Second Matrix:")
print(y)


mul = np.matmul(x,y)
print("Multiplication of two matrics")
print(mul)


add = np.add(x,y)
print("Addition of two matrics")
print(add)

sub = np.subtract(x,y)
print("Subtraction of two matrics")
print(sub)

div = np.divide(x,y)
print("Division of two matrics")
print(div)




First Matrix:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Second Matrix:
[[15 16 17]
 [18 19 20]
 [21 22 23]]
Multiplication of two matrics
[[ 654  690  726]
 [ 816  861  906]
 [ 978 1032 1086]]
Addition of two matrics
[[26 28 30]
 [32 34 36]
 [38 40 42]]
Subtraction of two matrics
[[-4 -4 -4]
 [-4 -4 -4]
 [-4 -4 -4]]
Division of two matrics
[[0.73333333 0.75       0.76470588]
 [0.77777778 0.78947368 0.8       ]
 [0.80952381 0.81818182 0.82608696]]
